import type { ImageManifestEntry } from "@/types/images";

// This file is regenerated by scripts/extract-colors.ts before each production build.
export const imageManifest = {
  "collage/collage-28699.jpg": {
    "source": "/images/collage/collage-28699.jpg",
    "width": 3900,
    "height": 4003,
    "dominantColor": "#767269",
    "blurDataUrl": "data:image/jpeg;base64,/9j/2wBDABELDA8MChEPDg8TEhEUGSobGRcXGTMkJh4qPDU/Pjs1OjlDS2BRQ0daSDk6U3FUWmNma2xrQFB2fnRofWBpa2f/2wBDARITExkWGTEbGzFnRTpFZ2dnZ2dnZ2dnZ2dnZ2dnZ2dnZ2dnZ2dnZ2dnZ2dnZ2dnZ2dnZ2dnZ2dnZ2dnZ2dnZ2f/wAARCAAQABADASIAAhEBAxEB/8QAFgABAQEAAAAAAAAAAAAAAAAABAED/8QAIhAAAgEEAQQDAAAAAAAAAAAAAQIEAxESIQAFIjJBcYGR/8QAFQEBAQAAAAAAAAAAAAAAAAAAAQL/xAAYEQADAQEAAAAAAAAAAAAAAAAAAQIxYf/aAAwDAQACEQMRAD8Ax6bGIiIAMWZNXJ0bcRVp0UgO0d38T3ObWOOz8cJAkpRgU8iSMDdl1b79ckydGerpMgRiquAcj7JH5vkw9Glw/9k="
  },
  "collage/collage-board-complete.png": {
    "source": "/images/collage/collage-board-complete.png",
    "width": 2382,
    "height": 1684,
    "dominantColor": "#CAC2C1",
    "blurDataUrl": "data:image/jpeg;base64,/9j/2wBDABELDA8MChEPDg8TEhEUGSobGRcXGTMkJh4qPDU/Pjs1OjlDS2BRQ0daSDk6U3FUWmNma2xrQFB2fnRofWBpa2f/2wBDARITExkWGTEbGzFnRTpFZ2dnZ2dnZ2dnZ2dnZ2dnZ2dnZ2dnZ2dnZ2dnZ2dnZ2dnZ2dnZ2dnZ2dnZ2dnZ2dnZ2f/wAARCAALABADASIAAhEBAxEB/8QAFgABAQEAAAAAAAAAAAAAAAAABQID/8QAIRAAAgIBBAIDAAAAAAAAAAAAAQIDEQAEBRITIWEUMYH/xAAUAQEAAAAAAAAAAAAAAAAAAAAB/8QAFhEBAQEAAAAAAAAAAAAAAAAAABEB/9oADAMBAAIRAxEAPwBnc931kc0sSusRU0qCix/cnSb1rWkjh5RNIx8owtgL9esd+Dpu0ydCcy3MsR5J+s3Ci7oXgdkf/9k="
  },
  "collage/collage-img-0953.jpg": {
    "source": "/images/collage/collage-img-0953.jpg",
    "width": 356,
    "height": 1206,
    "dominantColor": "#87766E",
    "blurDataUrl": "data:image/jpeg;base64,/9j/2wBDABELDA8MChEPDg8TEhEUGSobGRcXGTMkJh4qPDU/Pjs1OjlDS2BRQ0daSDk6U3FUWmNma2xrQFB2fnRofWBpa2f/2wBDARITExkWGTEbGzFnRTpFZ2dnZ2dnZ2dnZ2dnZ2dnZ2dnZ2dnZ2dnZ2dnZ2dnZ2dnZ2dnZ2dnZ2dnZ2dnZ2dnZ2f/wAARCAAQAAUDASIAAhEBAxEB/8QAFQABAQAAAAAAAAAAAAAAAAAAAAT/xAAfEAACAgIBBQAAAAAAAAAAAAABAgADBBESEyJhgcH/xAAUAQEAAAAAAAAAAAAAAAAAAAAD/8QAFxEBAQEBAAAAAAAAAAAAAAAAAQARAv/aAAwDAQACEQMRAD8AiycyrBfpPULLD3MSSNE+ol1j3qEUVtwA0pq0S3k/IhK7OdAZf//Z"
  },
  "collage/collage-img-3149.png": {
    "source": "/images/collage/collage-img-3149.png",
    "width": 1824,
    "height": 3464,
    "dominantColor": "#87624C",
    "blurDataUrl": "data:image/jpeg;base64,/9j/2wBDABELDA8MChEPDg8TEhEUGSobGRcXGTMkJh4qPDU/Pjs1OjlDS2BRQ0daSDk6U3FUWmNma2xrQFB2fnRofWBpa2f/2wBDARITExkWGTEbGzFnRTpFZ2dnZ2dnZ2dnZ2dnZ2dnZ2dnZ2dnZ2dnZ2dnZ2dnZ2dnZ2dnZ2dnZ2dnZ2dnZ2dnZ2f/wAARCAAQAAgDASIAAhEBAxEB/8QAFgABAQEAAAAAAAAAAAAAAAAAAAME/8QAIBAAAQQCAQUAAAAAAAAAAAAAAQACAxESITEEEzNBgf/EABUBAQEAAAAAAAAAAAAAAAAAAAME/8QAFREBAQAAAAAAAAAAAAAAAAAAEQD/2gAMAwEAAhEDEQA/AMc8DhAOob43VWjk0HVj6EVHPMUPbkLrxJGDdc+q4O0QDUpf/9k="
  },
  "collage/collage-img-4899.png": {
    "source": "/images/collage/collage-img-4899.png",
    "width": 1360,
    "height": 3737,
    "dominantColor": "#685B50",
    "blurDataUrl": "data:image/jpeg;base64,/9j/2wBDABELDA8MChEPDg8TEhEUGSobGRcXGTMkJh4qPDU/Pjs1OjlDS2BRQ0daSDk6U3FUWmNma2xrQFB2fnRofWBpa2f/2wBDARITExkWGTEbGzFnRTpFZ2dnZ2dnZ2dnZ2dnZ2dnZ2dnZ2dnZ2dnZ2dnZ2dnZ2dnZ2dnZ2dnZ2dnZ2dnZ2dnZ2f/wAARCAAQAAYDASIAAhEBAxEB/8QAFgABAQEAAAAAAAAAAAAAAAAAAAQF/8QAHxAAAgICAQUAAAAAAAAAAAAAAQIABAMRIQUSUZHw/8QAFQEBAQAAAAAAAAAAAAAAAAAAAgP/xAAXEQADAQAAAAAAAAAAAAAAAAAAAREh/9oADAMBAAIRAxEAPwDOx1ciFWdSFK8dvPuJV0y8tW9aYoxw5DtPI+3EniHWf//Z"
  },
  "photography-pages/photography-page-01.png": {
    "source": "/images/photography-pages/photography-page-01.png",
    "width": 2880,
    "height": 1620,
    "dominantColor": "#88939B",
    "blurDataUrl": "data:image/jpeg;base64,/9j/2wBDABELDA8MChEPDg8TEhEUGSobGRcXGTMkJh4qPDU/Pjs1OjlDS2BRQ0daSDk6U3FUWmNma2xrQFB2fnRofWBpa2f/2wBDARITExkWGTEbGzFnRTpFZ2dnZ2dnZ2dnZ2dnZ2dnZ2dnZ2dnZ2dnZ2dnZ2dnZ2dnZ2dnZ2dnZ2dnZ2dnZ2dnZ2f/wAARCAAJABADASIAAhEBAxEB/8QAFgABAQEAAAAAAAAAAAAAAAAAAwEF/8QAIxAAAQMDAgcAAAAAAAAAAAAAAQIDEQAEBRIhMTI0cXKBsf/EABQBAQAAAAAAAAAAAAAAAAAAAAL/xAAXEQADAQAAAAAAAAAAAAAAAAAAASEC/9oADAMBAAIRAxEAPwB7rNv2906lLiUKSVaC4kATIiY90D+RyGUvmbdq72dWiNCykTG+4HCt+45j3P2ox1jHkKWXKHSsP//Z"
  },
  "photography-pages/photography-page-02.png": {
    "source": "/images/photography-pages/photography-page-02.png",
    "width": 2880,
    "height": 1620,
    "dominantColor": "#303030",
    "blurDataUrl": "data:image/jpeg;base64,/9j/2wBDABELDA8MChEPDg8TEhEUGSobGRcXGTMkJh4qPDU/Pjs1OjlDS2BRQ0daSDk6U3FUWmNma2xrQFB2fnRofWBpa2f/2wBDARITExkWGTEbGzFnRTpFZ2dnZ2dnZ2dnZ2dnZ2dnZ2dnZ2dnZ2dnZ2dnZ2dnZ2dnZ2dnZ2dnZ2dnZ2dnZ2dnZ2f/wAARCAAJABADASIAAhEBAxEB/8QAFgABAQEAAAAAAAAAAAAAAAAABQEC/8QAJxAAAQIEAwkBAAAAAAAAAAAAAQIDAAQFERIhcQYjMzRBYXOhscH/xAAUAQEAAAAAAAAAAAAAAAAAAAAA/8QAFBEBAAAAAAAAAAAAAAAAAAAAAP/aAAwDAQACEQMRAD8AGqUtJtbN0x1LQRNLAJULbxOd76ZZ94JfBcxJwpPUWAB9CMu8Jjx/pi07n06H5Af/2Q=="
  },
  "photography-pages/photography-page-03.png": {
    "source": "/images/photography-pages/photography-page-03.png",
    "width": 2880,
    "height": 1620,
    "dominantColor": "#727273",
    "blurDataUrl": "data:image/jpeg;base64,/9j/2wBDABELDA8MChEPDg8TEhEUGSobGRcXGTMkJh4qPDU/Pjs1OjlDS2BRQ0daSDk6U3FUWmNma2xrQFB2fnRofWBpa2f/2wBDARITExkWGTEbGzFnRTpFZ2dnZ2dnZ2dnZ2dnZ2dnZ2dnZ2dnZ2dnZ2dnZ2dnZ2dnZ2dnZ2dnZ2dnZ2dnZ2dnZ2f/wAARCAAJABADASIAAhEBAxEB/8QAFQABAQAAAAAAAAAAAAAAAAAABwb/xAAiEAACAQQABwEAAAAAAAAAAAABAgQAAxESEyExMzVBc7H/xAAUAQEAAAAAAAAAAAAAAAAAAAAA/8QAFBEBAAAAAAAAAAAAAAAAAAAAAP/aAAwDAQACEQMRAD8AirgS3rqQx1yfYBpbg4uQ4ysrsOGnLY46CiK73GpngeKjfFPwUH//2Q=="
  },
  "photography-pages/photography-page-04.png": {
    "source": "/images/photography-pages/photography-page-04.png",
    "width": 2880,
    "height": 1620,
    "dominantColor": "#CCCCCC",
    "blurDataUrl": "data:image/jpeg;base64,/9j/2wBDABELDA8MChEPDg8TEhEUGSobGRcXGTMkJh4qPDU/Pjs1OjlDS2BRQ0daSDk6U3FUWmNma2xrQFB2fnRofWBpa2f/2wBDARITExkWGTEbGzFnRTpFZ2dnZ2dnZ2dnZ2dnZ2dnZ2dnZ2dnZ2dnZ2dnZ2dnZ2dnZ2dnZ2dnZ2dnZ2dnZ2dnZ2f/wAARCAAJABADASIAAhEBAxEB/8QAFgABAQEAAAAAAAAAAAAAAAAABQME/8QAIxAAAQIFAwUAAAAAAAAAAAAAAQIRAAMGEiEFEzEEMzRRgv/EABQBAQAAAAAAAAAAAAAAAAAAAAD/xAAUEQEAAAAAAAAAAAAAAAAAAAAA/9oADAMBAAIRAxEAPwB2swtWiIt3e+m7bd2z6y0XpIKTTnTCYVkuvMx3a8tzmFxxGfUPH+hAf//Z"
  },
  "photography-pages/photography-page-05.png": {
    "source": "/images/photography-pages/photography-page-05.png",
    "width": 2880,
    "height": 1620,
    "dominantColor": "#565656",
    "blurDataUrl": "data:image/jpeg;base64,/9j/2wBDABELDA8MChEPDg8TEhEUGSobGRcXGTMkJh4qPDU/Pjs1OjlDS2BRQ0daSDk6U3FUWmNma2xrQFB2fnRofWBpa2f/2wBDARITExkWGTEbGzFnRTpFZ2dnZ2dnZ2dnZ2dnZ2dnZ2dnZ2dnZ2dnZ2dnZ2dnZ2dnZ2dnZ2dnZ2dnZ2dnZ2dnZ2f/wAARCAAJABADASIAAhEBAxEB/8QAFwAAAwEAAAAAAAAAAAAAAAAAAwQFBv/EACIQAAICAQMEAwAAAAAAAAAAAAECAwQABREhBiIxMjRRcv/EABQBAQAAAAAAAAAAAAAAAAAAAAD/xAAUEQEAAAAAAAAAAAAAAAAAAAAA/9oADAMBAAIRAxEAPwCbos1Kvo12WwkLzBgI1cAtyANwD9ecJ1E9CfRKM1RIUmZu9UCh9tjyQMzZ9sYo/JP5wP/Z"
  },
  "photography-pages/photography-page-06.png": {
    "source": "/images/photography-pages/photography-page-06.png",
    "width": 2880,
    "height": 1620,
    "dominantColor": "#B1B1B1",
    "blurDataUrl": "data:image/jpeg;base64,/9j/2wBDABELDA8MChEPDg8TEhEUGSobGRcXGTMkJh4qPDU/Pjs1OjlDS2BRQ0daSDk6U3FUWmNma2xrQFB2fnRofWBpa2f/2wBDARITExkWGTEbGzFnRTpFZ2dnZ2dnZ2dnZ2dnZ2dnZ2dnZ2dnZ2dnZ2dnZ2dnZ2dnZ2dnZ2dnZ2dnZ2dnZ2dnZ2f/wAARCAAJABADASIAAhEBAxEB/8QAFwAAAwEAAAAAAAAAAAAAAAAAAgQFBv/EACMQAAEDAwIHAAAAAAAAAAAAAAQBAgMABiESQQURMTRRYXL/xAAUAQEAAAAAAAAAAAAAAAAAAAAA/8QAFBEBAAAAAAAAAAAAAAAAAAAAAP/aAAwDAQACEQMRAD8Ao3aJxGctkwZJEcUcGY4XORXu1L4x0orSjOYeS4qQpYdCIxCFdjPvflWo2pc/t0+koP/Z"
  },
  "photography-pages/photography-page-07.png": {
    "source": "/images/photography-pages/photography-page-07.png",
    "width": 2880,
    "height": 1620,
    "dominantColor": "#3A3C40",
    "blurDataUrl": "data:image/jpeg;base64,/9j/2wBDABELDA8MChEPDg8TEhEUGSobGRcXGTMkJh4qPDU/Pjs1OjlDS2BRQ0daSDk6U3FUWmNma2xrQFB2fnRofWBpa2f/2wBDARITExkWGTEbGzFnRTpFZ2dnZ2dnZ2dnZ2dnZ2dnZ2dnZ2dnZ2dnZ2dnZ2dnZ2dnZ2dnZ2dnZ2dnZ2dnZ2dnZ2f/wAARCAAJABADASIAAhEBAxEB/8QAFgABAQEAAAAAAAAAAAAAAAAABQIE/8QAIRAAAQQBAwUAAAAAAAAAAAAAAQIDBBEABRJBEyMzceH/xAAUAQEAAAAAAAAAAAAAAAAAAAAB/8QAFBEBAAAAAAAAAAAAAAAAAAAAAP/aAAwDAQACEQMRAD8AB0xmIuPIW+42HUjtpXdE1eTrCY/XQYuyttEIFcD7h/IzRB859HEP/9k="
  },
  "photography-pages/photography-page-08.png": {
    "source": "/images/photography-pages/photography-page-08.png",
    "width": 2880,
    "height": 1620,
    "dominantColor": "#BEB6AC",
    "blurDataUrl": "data:image/jpeg;base64,/9j/2wBDABELDA8MChEPDg8TEhEUGSobGRcXGTMkJh4qPDU/Pjs1OjlDS2BRQ0daSDk6U3FUWmNma2xrQFB2fnRofWBpa2f/2wBDARITExkWGTEbGzFnRTpFZ2dnZ2dnZ2dnZ2dnZ2dnZ2dnZ2dnZ2dnZ2dnZ2dnZ2dnZ2dnZ2dnZ2dnZ2dnZ2dnZ2f/wAARCAAJABADASIAAhEBAxEB/8QAFwAAAwEAAAAAAAAAAAAAAAAAAwQFBv/EACIQAAEDAgYDAAAAAAAAAAAAAAECAwQAEQUGEhMUQTE0cv/EABUBAQEAAAAAAAAAAAAAAAAAAAEC/8QAFhEBAQEAAAAAAAAAAAAAAAAAEQAh/9oADAMBAAIRAxEAPwCxmRuS7LTx3JaFJYJTtatBVfu3dBysJycYkclUoshgBO8VaSq/kX7rVUtP9cfQqTWXC//Z"
  },
  "photography-pages/photography-page-09.png": {
    "source": "/images/photography-pages/photography-page-09.png",
    "width": 2880,
    "height": 1620,
    "dominantColor": "#AFAAAB",
    "blurDataUrl": "data:image/jpeg;base64,/9j/2wBDABELDA8MChEPDg8TEhEUGSobGRcXGTMkJh4qPDU/Pjs1OjlDS2BRQ0daSDk6U3FUWmNma2xrQFB2fnRofWBpa2f/2wBDARITExkWGTEbGzFnRTpFZ2dnZ2dnZ2dnZ2dnZ2dnZ2dnZ2dnZ2dnZ2dnZ2dnZ2dnZ2dnZ2dnZ2dnZ2dnZ2dnZ2f/wAARCAAJABADASIAAhEBAxEB/8QAFgABAQEAAAAAAAAAAAAAAAAABAMG/8QAIBAAAgEEAgMBAAAAAAAAAAAAAQIDAAQFEQYSITRBcv/EABUBAQEAAAAAAAAAAAAAAAAAAAAB/8QAFREBAQAAAAAAAAAAAAAAAAAAABH/2gAMAwEAAhEDEQA/AG8ulyKZi0W1e7WIxHsISwXe/GyKpxKXInIzpfvcsqxAAysSpPb5v7qtXRr/ANcfoUWv/9k="
  },
  "photography-pages/photography-page-10.png": {
    "source": "/images/photography-pages/photography-page-10.png",
    "width": 2880,
    "height": 1620,
    "dominantColor": "#A2B9C8",
    "blurDataUrl": "data:image/jpeg;base64,/9j/2wBDABELDA8MChEPDg8TEhEUGSobGRcXGTMkJh4qPDU/Pjs1OjlDS2BRQ0daSDk6U3FUWmNma2xrQFB2fnRofWBpa2f/2wBDARITExkWGTEbGzFnRTpFZ2dnZ2dnZ2dnZ2dnZ2dnZ2dnZ2dnZ2dnZ2dnZ2dnZ2dnZ2dnZ2dnZ2dnZ2dnZ2dnZ2f/wAARCAAJABADASIAAhEBAxEB/8QAFwAAAwEAAAAAAAAAAAAAAAAAAQQFBv/EACIQAAEDAwMFAAAAAAAAAAAAAAECBBEAAxQGE0EhMTRhcv/EABQBAQAAAAAAAAAAAAAAAAAAAAL/xAAXEQADAQAAAAAAAAAAAAAAAAAAERIh/9oADAMBAAIRAxEAPwCpqkvQ+tY+WEbJk2QogGenbmhpIvsy6XinRRtCDeCgJn3zWppZ/wCOPoU7xAjWf//Z"
  },
  "photography-pages/photography-page-11.png": {
    "source": "/images/photography-pages/photography-page-11.png",
    "width": 2880,
    "height": 1620,
    "dominantColor": "#A9B0B1",
    "blurDataUrl": "data:image/jpeg;base64,/9j/2wBDABELDA8MChEPDg8TEhEUGSobGRcXGTMkJh4qPDU/Pjs1OjlDS2BRQ0daSDk6U3FUWmNma2xrQFB2fnRofWBpa2f/2wBDARITExkWGTEbGzFnRTpFZ2dnZ2dnZ2dnZ2dnZ2dnZ2dnZ2dnZ2dnZ2dnZ2dnZ2dnZ2dnZ2dnZ2dnZ2dnZ2dnZ2f/wAARCAAJABADASIAAhEBAxEB/8QAFgABAQEAAAAAAAAAAAAAAAAABAIG/8QAIRAAAQQBBAMBAAAAAAAAAAAAAQIDBBIABhETQQUVNHL/xAAVAQEBAAAAAAAAAAAAAAAAAAAAAf/EABYRAQEBAAAAAAAAAAAAAAAAAAARIf/aAAwDAQACEQMRAD8Afq4zvaxxHEzi4TYsX2Bt3XL0smY35eQmQqUpkMiqniupVv1bNVhp/wA4/Qwk2v/Z"
  },
  "photography-pages/photography-page-12.png": {
    "source": "/images/photography-pages/photography-page-12.png",
    "width": 2880,
    "height": 1620,
    "dominantColor": "#B9C6CF",
    "blurDataUrl": "data:image/jpeg;base64,/9j/2wBDABELDA8MChEPDg8TEhEUGSobGRcXGTMkJh4qPDU/Pjs1OjlDS2BRQ0daSDk6U3FUWmNma2xrQFB2fnRofWBpa2f/2wBDARITExkWGTEbGzFnRTpFZ2dnZ2dnZ2dnZ2dnZ2dnZ2dnZ2dnZ2dnZ2dnZ2dnZ2dnZ2dnZ2dnZ2dnZ2dnZ2dnZ2f/wAARCAAJABADASIAAhEBAxEB/8QAFwAAAwEAAAAAAAAAAAAAAAAAAQQFBv/EACAQAAICAQQDAQAAAAAAAAAAAAECAwQABiExQREjNHL/xAAUAQEAAAAAAAAAAAAAAAAAAAAC/8QAGBEAAwEBAAAAAAAAAAAAAAAAABESASH/2gAMAwEAAhEDEQA/ALeqrFyBUNNLDSMpHqViF3527w6XmtTK73RYSQKFIlDANvyPPeaDFr/zj9DFXEGcbP/Z"
  },
  "photography-pages/photography-page-13.png": {
    "source": "/images/photography-pages/photography-page-13.png",
    "width": 2880,
    "height": 1620,
    "dominantColor": "#ACBAC1",
    "blurDataUrl": "data:image/jpeg;base64,/9j/2wBDABELDA8MChEPDg8TEhEUGSobGRcXGTMkJh4qPDU/Pjs1OjlDS2BRQ0daSDk6U3FUWmNma2xrQFB2fnRofWBpa2f/2wBDARITExkWGTEbGzFnRTpFZ2dnZ2dnZ2dnZ2dnZ2dnZ2dnZ2dnZ2dnZ2dnZ2dnZ2dnZ2dnZ2dnZ2dnZ2dnZ2dnZ2f/wAARCAAJABADASIAAhEBAxEB/8QAFwAAAwEAAAAAAAAAAAAAAAAAAwQFBv/EACIQAAIBAwMFAQAAAAAAAAAAAAEDBAACEQYSQSEiMTRhcv/EABQBAQAAAAAAAAAAAAAAAAAAAAL/xAAXEQADAQAAAAAAAAAAAAAAAAAAESES/9oADAMBAAIRAxEAPwCvqeTITMXauNMasqybo5vGCD47eaHpNs26cwSVy7FhHQv3YJ3fecVqaWn+uP0KTiDms//Z"
  },
  "photography-pages/photography-page-14.png": {
    "source": "/images/photography-pages/photography-page-14.png",
    "width": 2880,
    "height": 1620,
    "dominantColor": "#B3B8BA",
    "blurDataUrl": "data:image/jpeg;base64,/9j/2wBDABELDA8MChEPDg8TEhEUGSobGRcXGTMkJh4qPDU/Pjs1OjlDS2BRQ0daSDk6U3FUWmNma2xrQFB2fnRofWBpa2f/2wBDARITExkWGTEbGzFnRTpFZ2dnZ2dnZ2dnZ2dnZ2dnZ2dnZ2dnZ2dnZ2dnZ2dnZ2dnZ2dnZ2dnZ2dnZ2dnZ2dnZ2f/wAARCAAJABADASIAAhEBAxEB/8QAFwAAAwEAAAAAAAAAAAAAAAAAAwQFBv/EACIQAAEDAwMFAAAAAAAAAAAAAAIAAQQDEUEFBhMSISI0cv/EABUBAQEAAAAAAAAAAAAAAAAAAAAB/8QAFxEAAwEAAAAAAAAAAAAAAAAAAAERMf/aAAwDAQACEQMRAD8Ar7heW2sR3pHKGlwv1cQk43vm2UPaYyh1GUUmtNMSHxGuJsLd8XytSlp/rt9MlJFp/9k="
  },
  "photography-pages/photography-page-15.png": {
    "source": "/images/photography-pages/photography-page-15.png",
    "width": 2880,
    "height": 1620,
    "dominantColor": "#D3DADF",
    "blurDataUrl": "data:image/jpeg;base64,/9j/2wBDABELDA8MChEPDg8TEhEUGSobGRcXGTMkJh4qPDU/Pjs1OjlDS2BRQ0daSDk6U3FUWmNma2xrQFB2fnRofWBpa2f/2wBDARITExkWGTEbGzFnRTpFZ2dnZ2dnZ2dnZ2dnZ2dnZ2dnZ2dnZ2dnZ2dnZ2dnZ2dnZ2dnZ2dnZ2dnZ2dnZ2dnZ2f/wAARCAAJABADASIAAhEBAxEB/8QAFwAAAwEAAAAAAAAAAAAAAAAAAwQFBv/EACMQAAEDAwIHAAAAAAAAAAAAAAECAwQABREGEhMhMTRBYXL/xAAUAQEAAAAAAAAAAAAAAAAAAAAB/8QAFhEBAQEAAAAAAAAAAAAAAAAAEQAh/9oADAMBAAIRAxEAPwDSaolvwrWh1gkOcZIyM+c9fVH0/JclWSM+/uDi0kq3nnnJqjS0/tx9Clwg1v/Z"
  },
  "photography-pages/photography-page-16.png": {
    "source": "/images/photography-pages/photography-page-16.png",
    "width": 2880,
    "height": 1620,
    "dominantColor": "#A8A6A9",
    "blurDataUrl": "data:image/jpeg;base64,/9j/2wBDABELDA8MChEPDg8TEhEUGSobGRcXGTMkJh4qPDU/Pjs1OjlDS2BRQ0daSDk6U3FUWmNma2xrQFB2fnRofWBpa2f/2wBDARITExkWGTEbGzFnRTpFZ2dnZ2dnZ2dnZ2dnZ2dnZ2dnZ2dnZ2dnZ2dnZ2dnZ2dnZ2dnZ2dnZ2dnZ2dnZ2dnZ2f/wAARCAAJABADASIAAhEBAxEB/8QAFgABAQEAAAAAAAAAAAAAAAAABAEG/8QAIxAAAQEHBAMAAAAAAAAAAAAAAQQAAgUREhNBAwYUMjRhcv/EABQBAQAAAAAAAAAAAAAAAAAAAAD/xAAUEQEAAAAAAAAAAAAAAAAAAAAA/9oADAMBAAIRAxEAPwBm8XokIuk4gV2LZuHQql29Zk12a8vMTVFYVo0rYo5FVPbE8tr2Mv8AHH0GD//Z"
  },
  "photography-pages/photography-page-17.png": {
    "source": "/images/photography-pages/photography-page-17.png",
    "width": 2880,
    "height": 1620,
    "dominantColor": "#B7C2CB",
    "blurDataUrl": "data:image/jpeg;base64,/9j/2wBDABELDA8MChEPDg8TEhEUGSobGRcXGTMkJh4qPDU/Pjs1OjlDS2BRQ0daSDk6U3FUWmNma2xrQFB2fnRofWBpa2f/2wBDARITExkWGTEbGzFnRTpFZ2dnZ2dnZ2dnZ2dnZ2dnZ2dnZ2dnZ2dnZ2dnZ2dnZ2dnZ2dnZ2dnZ2dnZ2dnZ2dnZ2f/wAARCAAJABADASIAAhEBAxEB/8QAFwAAAwEAAAAAAAAAAAAAAAAAAwQFBv/EACUQAAECBAQHAAAAAAAAAAAAAAEDEQAEEhMFIUFhAgYUFTE0cv/EABUBAQEAAAAAAAAAAAAAAAAAAAEC/8QAFxEAAwEAAAAAAAAAAAAAAAAAABEhEv/aAAwDAQACEQMRAD8Au43d7gmQZi0Es7VTPVtrAOW+qGKLFbimrJSyvVM9W+rRpR4hef8AXH0IrUQKs//Z"
  },
  "photography-pages/photography-page-18.png": {
    "source": "/images/photography-pages/photography-page-18.png",
    "width": 2880,
    "height": 1620,
    "dominantColor": "#BEC4C8",
    "blurDataUrl": "data:image/jpeg;base64,/9j/2wBDABELDA8MChEPDg8TEhEUGSobGRcXGTMkJh4qPDU/Pjs1OjlDS2BRQ0daSDk6U3FUWmNma2xrQFB2fnRofWBpa2f/2wBDARITExkWGTEbGzFnRTpFZ2dnZ2dnZ2dnZ2dnZ2dnZ2dnZ2dnZ2dnZ2dnZ2dnZ2dnZ2dnZ2dnZ2dnZ2dnZ2dnZ2f/wAARCAAJABADASIAAhEBAxEB/8QAFQABAQAAAAAAAAAAAAAAAAAABAX/xAAiEAACAQMDBQEAAAAAAAAAAAABAgMABAURMUEGEiE0UXH/xAAUAQEAAAAAAAAAAAAAAAAAAAAB/8QAFREBAQAAAAAAAAAAAAAAAAAAABH/2gAMAwEAAhEDEQA/AK3Utxk4sjAllHM0DxESFFY9p131HNMwc98bmWK6RxCqBkdwdSTx5+VZG1Hv/XH6KaI//9k="
  },
  "photography-pages/photography-page-19.png": {
    "source": "/images/photography-pages/photography-page-19.png",
    "width": 2880,
    "height": 1620,
    "dominantColor": "#B5AEAB",
    "blurDataUrl": "data:image/jpeg;base64,/9j/2wBDABELDA8MChEPDg8TEhEUGSobGRcXGTMkJh4qPDU/Pjs1OjlDS2BRQ0daSDk6U3FUWmNma2xrQFB2fnRofWBpa2f/2wBDARITExkWGTEbGzFnRTpFZ2dnZ2dnZ2dnZ2dnZ2dnZ2dnZ2dnZ2dnZ2dnZ2dnZ2dnZ2dnZ2dnZ2dnZ2dnZ2dnZ2f/wAARCAAJABADASIAAhEBAxEB/8QAFgABAQEAAAAAAAAAAAAAAAAABAUG/8QAJBAAAQEHAwUAAAAAAAAAAAAAAQIAAwQFERJBBhMiFBU0UXL/xAAUAQEAAAAAAAAAAAAAAAAAAAAB/8QAFhEBAQEAAAAAAAAAAAAAAAAAEQAh/9oADAMBAAIRAxEAPwCtqNEwXMnJg1xCXYdcrCba3H1ljaNEy7pFqjusDko4b5VSt2AW12GPH+OPoMGy4X//2Q=="
  },
  "photography-pages/photography-page-20.png": {
    "source": "/images/photography-pages/photography-page-20.png",
    "width": 2880,
    "height": 1620,
    "dominantColor": "#AFBAC5",
    "blurDataUrl": "data:image/jpeg;base64,/9j/2wBDABELDA8MChEPDg8TEhEUGSobGRcXGTMkJh4qPDU/Pjs1OjlDS2BRQ0daSDk6U3FUWmNma2xrQFB2fnRofWBpa2f/2wBDARITExkWGTEbGzFnRTpFZ2dnZ2dnZ2dnZ2dnZ2dnZ2dnZ2dnZ2dnZ2dnZ2dnZ2dnZ2dnZ2dnZ2dnZ2dnZ2dnZ2f/wAARCAAJABADASIAAhEBAxEB/8QAFwAAAwEAAAAAAAAAAAAAAAAAAgQFBv/EACMQAAIBAwIHAQAAAAAAAAAAAAEDBAACEQYTBRQhMTRBYXL/xAAUAQEAAAAAAAAAAAAAAAAAAAAC/8QAFxEAAwEAAAAAAAAAAAAAAAAAAAEREv/aAAwDAQACEQMRAD8Aq6pkz0cQTyi33WbRJ27biM5+e6LS8ue+c4TEuWsKBBZbcBnPbrWlpaf44/Qpacgcq0//2Q=="
  },
  "photography-pages/photography-page-21.png": {
    "source": "/images/photography-pages/photography-page-21.png",
    "width": 2880,
    "height": 1620,
    "dominantColor": "#B3BBC2",
    "blurDataUrl": "data:image/jpeg;base64,/9j/2wBDABELDA8MChEPDg8TEhEUGSobGRcXGTMkJh4qPDU/Pjs1OjlDS2BRQ0daSDk6U3FUWmNma2xrQFB2fnRofWBpa2f/2wBDARITExkWGTEbGzFnRTpFZ2dnZ2dnZ2dnZ2dnZ2dnZ2dnZ2dnZ2dnZ2dnZ2dnZ2dnZ2dnZ2dnZ2dnZ2dnZ2dnZ2f/wAARCAAJABADASIAAhEBAxEB/8QAFgABAQEAAAAAAAAAAAAAAAAABAUG/8QAIhAAAQMDAwUAAAAAAAAAAAAAAQIDBAAFEQYSMSEiNEFy/8QAFAEBAAAAAAAAAAAAAAAAAAAAAf/EABYRAQEBAAAAAAAAAAAAAAAAABEAIf/aAAwDAQACEQMRAD8At3+XJjXOOUMynWQ2SsMgkE56cUXSrs129TFyUTEMKRlAkbto7uBn3itXRp/jj6FLhBrf/9k="
  },
  "photography-pages/photography-page-22.png": {
    "source": "/images/photography-pages/photography-page-22.png",
    "width": 2880,
    "height": 1620,
    "dominantColor": "#AABAC2",
    "blurDataUrl": "data:image/jpeg;base64,/9j/2wBDABELDA8MChEPDg8TEhEUGSobGRcXGTMkJh4qPDU/Pjs1OjlDS2BRQ0daSDk6U3FUWmNma2xrQFB2fnRofWBpa2f/2wBDARITExkWGTEbGzFnRTpFZ2dnZ2dnZ2dnZ2dnZ2dnZ2dnZ2dnZ2dnZ2dnZ2dnZ2dnZ2dnZ2dnZ2dnZ2dnZ2dnZ2f/wAARCAAJABADASIAAhEBAxEB/8QAFwAAAwEAAAAAAAAAAAAAAAAAAAQFBv/EACEQAAAGAgEFAAAAAAAAAAAAAAABAgMEEQYTQQUUIjRy/8QAFAEBAAAAAAAAAAAAAAAAAAAAAv/EABcRAAMBAAAAAAAAAAAAAAAAAAABERL/2gAMAwEAAhEDEQA/AKuUuzW57JxmpLiNR3qUok3fNAxZ2cvqL/dtSW29XjtUoyu+LGnC0/1y+iC05A4Vp//Z"
  },
  "photography-pages/photography-page-23.png": {
    "source": "/images/photography-pages/photography-page-23.png",
    "width": 2880,
    "height": 1620,
    "dominantColor": "#C1CCD8",
    "blurDataUrl": "data:image/jpeg;base64,/9j/2wBDABELDA8MChEPDg8TEhEUGSobGRcXGTMkJh4qPDU/Pjs1OjlDS2BRQ0daSDk6U3FUWmNma2xrQFB2fnRofWBpa2f/2wBDARITExkWGTEbGzFnRTpFZ2dnZ2dnZ2dnZ2dnZ2dnZ2dnZ2dnZ2dnZ2dnZ2dnZ2dnZ2dnZ2dnZ2dnZ2dnZ2dnZ2f/wAARCAAJABADASIAAhEBAxEB/8QAFgABAQEAAAAAAAAAAAAAAAAABQIE/8QAIBAAAQMEAgMAAAAAAAAAAAAAAQIDBAAREkEFMTRDcv/EABQBAQAAAAAAAAAAAAAAAAAAAAL/xAAXEQADAQAAAAAAAAAAAAAAAAAAARES/9oADAMBAAIRAxEAPwB7nnVonMgImlOBJLGWPe7bquDfU7LcumWlIb96VAd6vunKzT/HH0KWnIHKtP/Z"
  },
  "work-05-self-collage.jpg": {
    "source": "/images/work-05-self-collage.jpg",
    "width": 5057,
    "height": 7150,
    "dominantColor": "#8A837F",
    "blurDataUrl": "data:image/jpeg;base64,/9j/2wBDABELDA8MChEPDg8TEhEUGSobGRcXGTMkJh4qPDU/Pjs1OjlDS2BRQ0daSDk6U3FUWmNma2xrQFB2fnRofWBpa2f/2wBDARITExkWGTEbGzFnRTpFZ2dnZ2dnZ2dnZ2dnZ2dnZ2dnZ2dnZ2dnZ2dnZ2dnZ2dnZ2dnZ2dnZ2dnZ2dnZ2dnZ2f/wAARCAAQAAsDASIAAhEBAxEB/8QAFQABAQAAAAAAAAAAAAAAAAAABAX/xAAjEAACAQQBAwUAAAAAAAAAAAABAgMABBEhEiIxQRNCYbHw/8QAFAEBAAAAAAAAAAAAAAAAAAAAAf/EABYRAQEBAAAAAAAAAAAAAAAAAAARQf/aAAwDAQACEQMRAD8ARbusKsAhjmKg4U5CjWqky2t9LK0h9xz1Lk/VVLa8jSykiE3Fk2MjkfGR+7UYKT1KyyA75euV7/HijTH/2Q=="
  }
} satisfies Readonly<Record<string, ImageManifestEntry>>;
