import { readdir, writeFile } from "node:fs/promises";
import path from "node:path";

import sharp from "sharp";

interface GeneratedImageEntry {
  readonly source: string;
  readonly width: number;
  readonly height: number;
  readonly dominantColor: `#${string}`;
  readonly blurDataUrl: `data:image/${string}`;
}

const workspaceDirectory = process.cwd();
const imagesDirectory = path.join(workspaceDirectory, "public", "images");
const manifestPath = path.join(workspaceDirectory, "content", "image-manifest.generated.ts");
const supportedExtensions = new Set([".avif", ".jpeg", ".jpg", ".png", ".webp"]);

async function collectImagePaths(directory: string): Promise<readonly string[]> {
  const directoryEntries = await readdir(directory, { withFileTypes: true });
  const nestedPaths = await Promise.all(
    directoryEntries.map(async (directoryEntry) => {
      const entryPath = path.join(directory, directoryEntry.name);

      if (directoryEntry.isDirectory()) {
        return collectImagePaths(entryPath);
      }

      const extension = path.extname(directoryEntry.name).toLowerCase();
      return supportedExtensions.has(extension) ? [entryPath] : [];
    }),
  );

  return nestedPaths.flat().sort((firstPath, secondPath) => firstPath.localeCompare(secondPath));
}

function channelToHex(channel: number): string {
  return channel.toString(16).padStart(2, "0").toUpperCase();
}

async function extractImageEntry(imagePath: string): Promise<GeneratedImageEntry> {
  const normalizedImage = sharp(imagePath).rotate().toColorspace("srgb");
  const metadata = await normalizedImage.metadata();

  if (metadata.width === undefined || metadata.height === undefined) {
    throw new Error(`Image dimensions could not be read: ${imagePath}`);
  }

  // One-pixel sampling happens at build time so pointer movement never triggers canvas work.
  const dominantPixel = await normalizedImage
    .clone()
    .resize(1, 1, { fit: "fill" })
    .removeAlpha()
    .raw()
    .toBuffer();
  const red = dominantPixel[0];
  const green = dominantPixel[1];
  const blue = dominantPixel[2];

  if (red === undefined || green === undefined || blue === undefined) {
    throw new Error(`Dominant color could not be sampled: ${imagePath}`);
  }

  // The tiny JPEG preserves a dark image's tonal character instead of flashing a pale placeholder.
  const blurBuffer = await normalizedImage
    .clone()
    .resize({ width: 16, height: 16, fit: "inside", withoutEnlargement: true })
    .jpeg({ quality: 48, chromaSubsampling: "4:2:0" })
    .toBuffer();
  const relativePath = path.relative(imagesDirectory, imagePath).split(path.sep).join("/");

  return {
    source: `/images/${relativePath}`,
    width: metadata.width,
    height: metadata.height,
    dominantColor: `#${channelToHex(red)}${channelToHex(green)}${channelToHex(blue)}`,
    blurDataUrl: `data:image/jpeg;base64,${blurBuffer.toString("base64")}`,
  };
}

function serializeManifest(entries: Readonly<Record<string, GeneratedImageEntry>>): string {
  return [
    'import type { ImageManifestEntry } from "@/types/images";',
    "",
    "// This file is regenerated by scripts/extract-colors.ts before each production build.",
    `export const imageManifest = ${JSON.stringify(entries, null, 2)} satisfies Readonly<Record<string, ImageManifestEntry>>;`,
    "",
  ].join("\n");
}

async function generateImageManifest(): Promise<void> {
  const imagePaths = await collectImagePaths(imagesDirectory);
  const imageEntries = await Promise.all(imagePaths.map(extractImageEntry));
  const manifest = Object.fromEntries(
    imagePaths.map((imagePath, index) => {
      const relativePath = path.relative(imagesDirectory, imagePath).split(path.sep).join("/");
      const imageEntry = imageEntries[index];

      if (imageEntry === undefined) {
        throw new Error(`Generated image entry is missing: ${relativePath}`);
      }

      return [relativePath, imageEntry];
    }),
  );

  await writeFile(manifestPath, serializeManifest(manifest), "utf8");
}

await generateImageManifest();
